net-firewall/shorewall*: v4.5.21.2 added
Changelog
=========
1)  The Broadcast actions have been corrected:

    o --dst-type BROADCAST has been removed from the IPv6 version
    o A superfluous DROP rule in the IPv4 version has been suppressed.

2)  Previously, if an HFSC class was specified with dmax but not umax,
    then the firewall would fail to start with the messages:

      Nov 14 13:42:42 Setting up Traffic Control...
      HFSC: Illegal "umax"
      HFSC: Illegal "sc"
      ERROR: Command "tc class add dev eth1 parent 1:1 classid 1:110 hfsc sc
         umax b dmax 150ms rate 1575kbit ul rate 3150kbit" Failed

    That problem has been corrected.

Full changelogs: http://www1.shorewall.net/pub/shorewall/4.5/shorewall-4.5.21/releasenotes.txt